package rdpgfx

import (
	"os"
	"testing"
)

// These tests replay messages captured from a real Windows server rather than
// constructed by hand, which turned out to matter here.
//
// The synthetic PDUs in rdpgfx_test.go once shared a misreading of the
// WireToSurface header with the parser: both had an extra byte between the
// pixel format and the destination rectangle. Since the test wrote the bytes the
// parser expected, it passed, and both were wrong in the same way. Only real
// traffic showed it, because the destination rectangle shifted by a byte reads
// as a nonsense length (0xC000001D) and every update is dropped.
//
// The fixtures are the fixed bytes of that message. They are not regenerated by
// a script: they come from a capture, and their value is that they were not
// written by us.

func readFixture(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile("testdata/" + name)
	if err != nil {
		t.Fatalf("fixture %s: %v", name, err)
	}
	return b
}

// TestWireToSurfaceRealWindowsMessage replays a CreateSurface followed by a
// WireToSurface1 that places a RemoteFX tile in the bottom right corner.
func TestWireToSurfaceRealWindowsMessage(t *testing.T) {
	create := readFixture(t, "windows_createsurface.bin")
	wire := readFixture(t, "windows_wiretosurface.bin")

	c, _ := newTestClient(t)
	feed(c, create)
	feed(c, wire)

	c.mu.Lock()
	s := c.surfaces[0]
	c.mu.Unlock()
	if s == nil {
		t.Fatal("the captured message did not create a surface")
	}
	if s.Width != 1024 || s.Height != 768 {
		t.Fatalf("surface is %dx%d, want 1024x768", s.Width, s.Height)
	}

	// The captured message says 48x40 at (971,728).
	const (
		left, top     = 971, 728
		right, bottom = 1019, 768
	)
	pixels := s.Pixels()

	inside := false
	for y := top; y < bottom && !inside; y++ {
		for x := left; x < right; x++ {
			if o := (y*s.Width + x) * 4; pixels[o] != 0 || pixels[o+1] != 0 || pixels[o+2] != 0 {
				inside = true
				break
			}
		}
	}
	if !inside {
		t.Error("nothing was drawn where the destination rectangle says it should be")
	}

	// Nothing may land outside it. Reading the rectangle one byte early or late
	// moves it, and that is exactly the failure this fixture caught.
	for y := 0; y < top; y++ {
		for x := 0; x < s.Width; x++ {
			if o := (y*s.Width + x) * 4; pixels[o] != 0 || pixels[o+1] != 0 || pixels[o+2] != 0 {
				t.Fatalf("pixel at (%d,%d) is outside the destination rectangle and should be untouched", x, y)
			}
		}
	}
}

// The captured messages must keep the shape the parser relies on: the fixed
// part is 17 bytes with no gap between the pixel format and the rectangle, and
// the declared length is exactly what follows it.
func TestWireToSurfaceFixtureLayout(t *testing.T) {
	wire := readFixture(t, "windows_wiretosurface.bin")
	if len(wire) < headerSize+17 {
		t.Fatalf("fixture is only %d bytes", len(wire))
	}
	body := wire[headerSize:]

	if got := u32At(body, 13); int(got) != len(body)-17 {
		t.Errorf("declared length %d, but %d bytes follow the fixed part", got, len(body)-17)
	}
	// RemoteFX payloads begin with a WBT_SYNC block: the block type, then the
	// block length, then a version. The block starting at 17 is the whole point.
	if body[17] != 0xc0 || body[18] != 0xcc {
		t.Errorf("payload starts with %02x %02x, want the RFX sync marker c0 cc", body[17], body[18])
	}
	if got := u32At(body, 19); got != 12 {
		t.Errorf("sync block length is %d, want 12", got)
	}
	if got := u16At(body, 27); got != 0x0100 {
		t.Errorf("RFX version is 0x%04x, want 0x0100", got)
	}
	// The capture is from a 1024x768 desktop, so the rectangle has to be inside
	// it, and this one sits in the bottom right corner.
	left, top := int(u16At(body, 5)), int(u16At(body, 7))
	right, bottom := int(u16At(body, 9)), int(u16At(body, 11))
	if left != 971 || top != 728 || right != 1019 || bottom != 768 {
		t.Errorf("destination rectangle is (%d,%d,%d,%d), want (971,728,1019,768)", left, top, right, bottom)
	}
}

func u16At(b []byte, off int) uint16 { return uint16(b[off]) | uint16(b[off+1])<<8 }

func u32At(b []byte, off int) uint32 {
	return uint32(b[off]) | uint32(b[off+1])<<8 | uint32(b[off+2])<<16 | uint32(b[off+3])<<24
}

// TestMapSurfaceToOutputRealWindowsMessage replays the mapping command from the
// same capture, which places the main desktop surface at the origin.
func TestMapSurfaceToOutputRealWindowsMessage(t *testing.T) {
	c, _ := newTestClient(t)
	feed(c, readFixture(t, "windows_createsurface.bin"))
	feed(c, readFixture(t, "windows_mapsurface.bin"))

	c.mu.Lock()
	s := c.surfaces[0]
	c.mu.Unlock()
	if s == nil {
		t.Fatal("surface 0 was not created")
	}
	if x, y := s.Origin(); x != 0 || y != 0 {
		t.Errorf("surface is mapped at (%d,%d), want (0,0)", x, y)
	}
}
